added video translation DVM spec
nostr-protocol/data-vending-machines pull request #3
Opened 2023-10-23 05:30 UTC by happylemonprogramming

Created data vending machine standard for video translation job requests

2023-10-23 06:15 UTC, pablof7z commented
We're missing a link from the ranges/52xx file to this one now

2023-10-24 03:29 UTC, happylemonprogramming commented
I think I updated "ranges" file to reference the video translation kind. I also formatted the language IDs to be a bit cleaner. Let me know if I missed anything else. Thanks!

2023-10-26 06:57 UTC, pablof7z requested changes

2023-10-26 06:57 UTC, pablof7z commented on kinds/5201.md
> +[ "param", "format", "mp4" ]
This should be an output tag instead of a param

`[ "output", "video/mp4" ]

2023-10-26 20:10 UTC, merged